LearningWebBackend/LearningWebBackend/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LearningWebBackend.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            string name = "Jesper";

            DateTime birthdate = new DateTime(1992, 04, 16);

            int age = DateTime.Today.Year - birthdate.Year;

            ViewData["name"] = name;
            ViewData["age"] = age;
            ViewData["birthday"] = birthdate.Day;
            ViewData["birthmonth"] = birthdate.Month;
            ViewData["birthyear"] = birthdate.Year;

            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

LearningWebBackend/LearningWebBackend/Controllers/RockbandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Collections;

namespace LearningWebBackend.Controllers
{
    public class RockbandController : Controller
    {
        public IActionResult Index()
        {
            List<string> bandlist = new List<string>();

            bandlist.Add("bandA");

            bandlist[0] = "null";

            string[] bandsB = new string[10];


            string[] bandnames = new string[]{ "a", "b", "c","d" };


            ViewData["bands"] = bandnames;


            return View();
        }
    }
}

LearningWebBackend/LearningWebBackend/Controllers/TimeCalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace LearningWebBackend.Controllers
{
    public class TimeCalculatorController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }

        public int tal()
        {
            return 5;
        }

        [HttpPost]
        public IActionResult Index(IFormCollection formCollection)
        {
            int hours = Convert.ToInt32(formCollection["Hours"]);
            int minutes = Convert.ToInt32(formCollection["Minutes"]);
            int seconds = Convert.ToInt32(formCollection["Seconds"]);
            TimeSpan ts = new TimeSpan(0, hours, minutes, seconds);
            double total = ts.TotalSeconds;

            ViewData["Hours"] = hours;
            ViewData["Minutes"] = minutes;
            ViewData["Seconds"] = seconds;

            ViewData["TotalTime"] = ts.TotalMinutes;
            return View();
        }

        [HttpPost]
        public IActionResult Restart(IFormCollection formCollection)
        {
            ViewData["TotalTime"] = null;
            Index();
            return View();
        }
    }
}

LearningWebBackend/LearningWebBackend/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1>@ViewData["Title"]</h1>
<a href="/home/Index">Home</a>
<h1>test</h1>

LearningWebBackend/LearningWebBackend/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h1>@ViewData["name"]</h1>
<h1>@ViewData["age"]</h1>
<h1>@String.Format("Fødselsdato: {0}/{1}/{2}",ViewData["birthday"], ViewData["birthmonth"], ViewData["birthyear"])</h1>

<a href="/rockband">Rockbands</a>

<a href="/TimeCalculator">Time calc</a>

<li><a asp-area="about" asp-controller="Home" asp-action="About">Home</a></li>

LearningWebBackend/LearningWebBackend/Views/Rockband/Index.cshtml
@{
	ViewData["Title"] = "Index";
}

<h2>Index</h2>
<h1>ViewData[bands]</h1>

@foreach(string name in ViewData["bands"] as string[] )
{
	<h1>@name</h1>
}

LearningWebBackend/LearningWebBackend/Views/TimeCalculator/Index.cshtml
@addTagHelper "*, Microsoft.ASPNetCore.Mvc.TagHelpers"

	@if (ViewData["TotalTime"] == null)
	{
		<form method="post" asp-controller="TimeCalculator" asp-action="Index">
			<div>
				<label for="Hours">Hours: </label> <br />
				<input type="text" name="Hours" />
			</div>
	
			<div>
				<label for="Hours">Minutes: </label> <br />
				<input type="text" name="Minutes" />
			</div>

			<div>
				<label for="Hours">Seconds: </label> <br />
				<input type="text" name="Seconds" />
			</div>
			<div>
				<input type="submit" value="Calculate time" />
			</div>
		</form>
	}
	else
	{
		@String.Format("{0} hours + {1} minutes + {2} seconds = {3} Minutes", ViewData["Hours"], ViewData["Minutes"], ViewData["Seconds"], ViewData["TotalTime"])
		<form method="post" asp-controller="TimeCalculator" asp-action="Restart"
		<div>
			<input type="submit" value="Reset" />
		</div>
	}